# Generated by Django 3.2.13 on 2022-05-05 11:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_date',
            field=models.DateField(blank=True, help_text='The date to use for the newsletter.', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_first_story',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The first story to use for the newsletter.', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_introduction',
            field=models.TextField(blank=True, help_text='The introduction to use for the newsletter.', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_receiver',
            field=models.CharField(blank=True, help_text='The receiver of the newsletter.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_second_story',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The first story to use for the newsletter.', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_third_story',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The first story to use for the newsletter.', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='second_story_image',
            field=models.ForeignKey(blank=True, help_text='The image to use for the second story.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
