# Generated by Django 4.0.4 on 2022-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_current_need_homepage_page_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecards',
            name='lead',
        ),
        migrations.AddField(
            model_name='homepage',
            name='current_need_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
