# Generated by Django 4.0.4 on 2022-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepagecards_lead_homepage_current_need_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecards',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
