# Generated by Django 4.0.4 on 2022-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_discipleshippage_educationpage_skillingpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipleshippage',
            name='featured_image_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='educationpage',
            name='featured_image_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skillingpage',
            name='featured_image_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
