# Generated by Django 3.2.13 on 2022-05-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0014_crisispagefaqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisispage',
            name='side_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='CrisisPageCarousel',
        ),
    ]
