# Generated by Django 3.2.13 on 2022-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_sponsorshippage_sponsorshippageformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
            },
        ),
    ]
