# Generated by Django 4.0.4 on 2022-04-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorpage',
            name='child_photo',
        ),
        migrations.RemoveField(
            model_name='sponsorpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='SponsorListingPage',
        ),
        migrations.DeleteModel(
            name='SponsorPage',
        ),
    ]
