# Generated by Django 4.0.4 on 2022-04-28 17:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpage',
            name='call_to_action',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
