# Generated by Django 4.0.4 on 2022-05-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('sponsorship', '0005_aboutpage_volunteerpage_aboutpagestrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='side_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
