# Generated by Django 3.2.13 on 2022-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0007_auto_20220505_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorpage',
            name='child_DOB',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
    ]
