# Generated by Django 3.2.13 on 2022-06-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0009_professionlistingpage_twinningbeneficiarypage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twinningbeneficiarypage',
            old_name='beneficiary_DOB',
            new_name='Career_of_interest',
        ),
    ]
